PROGRAM 1:
---------------------------------------------------------------
import java.util.*;
public class exception1
{
 public static void main(String args[])
 {
  Scanner sc=new Scanner(System.in);
  int a=sc.nextInt();
  int b=sc.nextInt();
  try
  {
   double res=a/b;
   System.out.println(res);
  }
  catch(ArithmeticException e)
  {
   System.out.println("Denominator should not be Zero");
  }
 }
}
OUTPUT 1 :
-------------------------------------------
25
0
Denominator should not be Zero
OUTPUT 2:
------------------------------------------
24
4
6.0

PROGRAM 2:
------------------------------------------------
public class exception2
{
 public static void main(String args[])
 {
  String str=null;
  try
  {
   System.out.println(str.charAt(0));
  }
  catch(NullPointerException e)
  {
   System.out.println("Null Pointer Exception ");
  }
 }
} 

OUTPUT :
------------------------------
Null Pointer Exception


PROGRAM 3:
----------------------------------------------------------
import java.io.*;
public class exception3 
{
  public static void main(String[] args) 
  {
    File file = new File("abcd.txt");
    FileInputStream fn = null;
    try
    {
      fn = new FileInputStream(file);
      while (fn.read()!=-1)
      {
        System.out.println(fn.read());
      }
    }
    catch (FileNotFoundException e)
    {
     e.printStackTrace();
    }
    catch(IOException e)
    {
     e.printStackTrace();
    }
  }
}

OUTPUT :
-------------------------------------------------------
java.io.FileNotFoundException: abcd.txt (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at exception3.main(exception3.java:10)


PROGRAM 4:
-------------------------------------------------------------
import java.util.*; 
public class exception4 
{
 public static void main(String[] args)
 {
  Scanner sc = new Scanner(System.in);
  try
  {
   char c = sc.nextLine().charAt(4);
   System.out.println(c);
  }
  catch(Exception e)
  {
   System.out.println("Caught exception : "+e.toString());
  }
 }
}

OUTPUT :
---------------------------------------------------------
hai
Caught exception : java.lang.StringIndexOutOfBoundsException: String index out of range: 4


PROGRAM 5:
---------------------------------------------------------
import java.util.*;
class exception5
{
 public static void main(String[] args)
 {
  Scanner sc=new Scanner(System.in);
  int arr[]=new int[]{3,5,7,6};
  int n=sc.nextInt();
  try
  {
   int index=arr[n];
   System.out.println(index);  
  }  
  catch(Exception e)
  {
   System.out.println(e);
  }
  finally
  {
   System.out.println("Final Block");
  }
 }
}

OUTPUT :
------------------------------------------------------
2
7
Final Block

OUTPUT:
--------------------------------------------
5
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
Final Block